# Generated by Django 5.2.6 on 2025-09-20 03:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("designer", "设计助理"),
                            ("pattern_maker", "版房师傅"),
                            ("admin", "管理员"),
                        ],
                        default="designer",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="电话号码"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=50, verbose_name="部门"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "bom_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bom",
            fields=[
                (
                    "style_code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="款式编码",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="产品名称"),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SPRING", "春季"),
                            ("SUMMER", "夏季"),
                            ("AUTUMN", "秋季"),
                            ("WINTER", "冬季"),
                        ],
                        max_length=20,
                        verbose_name="季节",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                ("wave", models.CharField(max_length=50, verbose_name="波段")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TOP", "上衣"),
                            ("BOTTOM", "下装"),
                            ("DRESS", "连衣裙"),
                            ("OUTERWEAR", "外套"),
                            ("ACCESSORY", "配饰"),
                        ],
                        max_length=20,
                        verbose_name="品类",
                    ),
                ),
                (
                    "dev_colors",
                    models.TextField(
                        help_text="多个颜色用/分隔，如：黑色/白色/红色",
                        verbose_name="开发颜色",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="目标价格",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预估成本",
                    ),
                ),
                (
                    "fabric_composition",
                    models.TextField(blank=True, verbose_name="面料成分"),
                ),
                (
                    "fabric_weight",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="面料克重"
                    ),
                ),
                (
                    "care_instructions",
                    models.TextField(blank=True, verbose_name="洗护说明"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PENDING_CRAFT", "待填写工艺"),
                            ("PENDING_PATTERN", "待版房确认"),
                            ("CONFIRMED", "已确认"),
                            ("REVISED", "已修订"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本号"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_boms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_boms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM列表",
                "db_table": "bom_main",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BomDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField(verbose_name="序号")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("FABRIC", "面料"),
                            ("LINING", "里料"),
                            ("INTERLINING", "衬布"),
                            ("THREAD", "缝纫线"),
                            ("BUTTON", "纽扣"),
                            ("ZIPPER", "拉链"),
                            ("LABEL", "标签"),
                            ("TRIM", "辅料"),
                            ("ELASTIC", "松紧带"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="物料类型",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="物料名称"),
                ),
                (
                    "material_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="物料编码"
                    ),
                ),
                ("specification", models.TextField(verbose_name="规格描述")),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=200, verbose_name="供应商"),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="供应商编码"
                    ),
                ),
                (
                    "usage_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="用量",
                    ),
                ),
                (
                    "usage_unit",
                    models.CharField(
                        choices=[
                            ("M", "米"),
                            ("KG", "千克"),
                            ("PCS", "个"),
                            ("PAIR", "对"),
                            ("SET", "套"),
                            ("ROLL", "卷"),
                            ("YARD", "码"),
                        ],
                        max_length=10,
                        verbose_name="单位",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="单价",
                    ),
                ),
                (
                    "color_requirement",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="颜色要求"
                    ),
                ),
                (
                    "craft_requirement",
                    models.TextField(blank=True, verbose_name="工艺要求"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="boms.bom",
                        verbose_name="所属BOM",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM明细",
                "verbose_name_plural": "BOM明细",
                "db_table": "bom_detail",
                "ordering": ["bom", "sequence"],
                "unique_together": {("bom", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="SizeSpec",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XXS", "XXS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                        ],
                        max_length=10,
                        verbose_name="尺码",
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        default=dict,
                        help_text='存储各部位尺寸，如：{"胸围": 108, "肩宽": 45, "袖长": 60}',
                        verbose_name="尺寸规格",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_specs",
                        to="boms.bom",
                        verbose_name="所属BOM",
                    ),
                ),
            ],
            options={
                "verbose_name": "尺码规格",
                "verbose_name_plural": "尺码规格",
                "db_table": "bom_size_spec",
                "ordering": ["bom", "sort_order", "size"],
                "unique_together": {("bom", "size")},
            },
        ),
    ]
