# Generated by Django 5.2.6 on 2025-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("PENDING_CRAFT", "待填写工艺"),
                    ("PENDING_PATTERN", "待版房确认"),
                    ("PENDING_DETAILS", "待填写明细"),
                    ("CONFIRMED", "已确认"),
                    ("REVISED", "已修订"),
                    ("CANCELLED", "已取消"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
